### PR TITLE
BUG FIX: issue #7

### PR DESCRIPTION
**Pull request by phadkesharan**
Issue of 0 appearing when no videos added fixed by using conditional operator to render template literal conditionally

### CODE REVIEW

**Comment by phadkesharan** [comment]
I have also resolved issue #17 , Once you merge this I will also open that pull request

**Comment by RodrigoWebDev** [comment]
I'm sorry phadkesharan, I did not see your pull request and fixed the issue my self :(. your solution is great. For my solution, basically I changed `playlist.length`(that works well with React but not Preact) to `playlist.length > 0`  :). Thank you very much to collaborate and sorry again to not saw your pull request before :(

**Comment by RodrigoWebDev** [comment]
and please, can you open a pull request with the #17 that you said you resolved?

**Comment by phadkesharan** [comment]
Its ok no problem! I will create a pull request for #17

**Pull request closed without merging**
